#!/usr/bin/env bash
# configures a new HAproxy as a load balancer

# Install HAproxy on a server
sudo apt-get -y update
sudo apt-get -y install haproxy=1.6.\*

# Configure haproxy configuration file to distribute requests using a roundrobin algorithm
echo '
frontend zahra-frontend
        bind 0:80
        default_backend zahra-backend
backend zahra-backend
        balance roundrobin
        server 98142-web-01 100.25.36:180
        server 98142-web-02 54.236.33.24
' >> /etc/haproxy/haproxy.cfg

# Restart HAproxy service
service haproxy restart
